default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: qmio_dev

test:
  <<: *default
  database: qmio_test

production:
  <<: *default
  database: quickmodio
